id: PAA90CCBB
initial_creation_type: ocr
source_metadata:
  volumes:
    ab543a9dd7364880b8ef4b83b55da273:
      base_file: v014.txt
      image_group_id: I1PD95859
      title: དཔལ་ནག་པོ་ཆེན་པོ་ཡུམ་ཅན་གྱི་སྒྲུབ་ཐབས།
      total_pages: 1856
      volume_number: 14
